name: "default"
description: "Default minimal profile - basic HTTP traffic"

http:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  
  headers:
    Accept: "*/*"
    Accept-Language: "en-US,en;q=0.9"
    Accept-Encoding: "gzip, deflate"
    
  get:
    uri:
      - "/api/get"
      - "/check"
      - "/status"
      - "/ping"
    headers:
      Cache-Control: "no-cache"
    transform:
      encode: "base64"
      
  post:
    uri:
      - "/api/post"
      - "/update"
      - "/submit"
      - "/sync"
    headers:
      Content-Type: "application/octet-stream"
    transform:
      encode: "base64"

timing:
  sleep: 60
  jitter: 25  # augmente legerement
  max_retry: 3

ssl:
  verify: false
